spring:
  application:
    name: quan-ly
  datasource:
    url: jdbc:postgresql://localhost:5432/quan-ly
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    open-in-view: false #quyết định việc liệu Hibernate Session (hoặc EntityManager) có được giữ mở trong suốt quá trình xử lý một request web hay không
    properties:
      hibernate:
        format_sql: true
  mail:
    port: 587
    host: smtp.gmail.com
    username: dangvanthinh372004@gmail.com
    password: "zsdd brth onhv csue"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


server:
  address: 0.0.0.0
  port: 8080

jwt:
  serect-key: "ZjhjZDg0NGU4MGExYmE1MDdkZjQyMDM4OTBjMTY5MmNiNzM0YWUzM2M4YTE1NjkyNzA4YjljNTgxMzFkMDNjYw"
